"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.cardABI = exports.setABI = exports.setsName = exports.dataPath = exports.mainAddress = exports.mainABI = void 0;
var mainJSON = require("../../contracts/artifacts/src/Admin.sol/Admin.json");
exports.mainABI = mainJSON.abi;
exports.mainAddress = '00x5fbdb2315678afecb367f032d93f642f64180aa3';
exports.dataPath = "../../data/";
exports.setsName = ["Base", "Fossil", "Jungle", "Wizards Black Star Promos"];
var setJSON = require("../../contracts/artifacts/src/Collection.sol/Collection.json");
exports.setABI = setJSON.abi;
var cardJSON = require("../../contracts/artifacts/src/NFT.sol/NFT.json");
exports.cardABI = cardJSON.abi;
